### ISSUE TITLE
Enhance `@typescript-eslint/no-use-before-define` by adding options

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/eslint-config#10]
Disabling `@typescript-eslint/no-use-before-define` completely is not good for safe code. Without it, we can write a code where variables are used before being defined.

I guess this rules is currently disabled to make it possible to define TypeScript things (e.g. type definitions) in arbitrary places in the code, because type definitions are likely to refer to each other.

Fortunately, `@typescript-eslint/no-use-before-define` rule has options by which we can prevent variables from being used before being defined while TypeScript things can be defined in any order.

```typescript
module.exports = {
  rules: {
    'no-use-before-define': 'off',
    '@typescript-eslint/no-use-before-define': [
      'error', 
      {
        ignoreTypeReferences: true
      }
    ]
  }
};
```

**Comment by kiaking** [comment]
Hah, could you test this rule by applying to things like Deus and Fatima, maybe? If it doesn't break anything, I think we can add this rule 👍 

However, I like to keep it to make to be able to define something like this though.

```ts
function foo() {
  bar() // bar is called before `bar` declaration but I want this to be OK.
}

function bar() {
 // ...
}
```

**Comment by NozomuIkuta** [comment]
Hmm, it seems that this rule doesn't work in some cases in `<script setup>` 😑 

```vue
<script setup lang="ts">
export function useAuth(): Auth {
  const { ready } = useRequireAuth() // -> `useRequireAuth` is treated as "use-before-define"
}

export const useRequireAuth = ...
</script>
```

```vue
<script setup lang="ts">
const showDisplay = computed(() => {
  return displayValue.value // -> `displayValue` is treated as "use-before-define"
})

const displayValue = computed(() => {...})
</script>
```

This might have been reported in somewhere (e.g. eslint-plugin-vue repo), so I will look for it when I have time.

For the time being, I will apply this rule to Kadomony Crawler only, because the rule by itself makes the normal JS/TS code much safer and reasonable.

---

By the way, just for your reference, `@typescript-eslint/no-use-before-define` inherits [some options from the original `no-use-before-define` rule](https://eslint.org/docs/latest/rules/no-use-before-define#options).

So, without the edge cases in `<script setup>`, we can set up some options to achieve what you need (using functions before their definitions), while we prevent variables from being used.

Here is how I set up the rule to test it with Deus code base.

```javascript
module.exports = {
    "@typescript-eslint/no-use-before-define": ["error", {
      "ignoreTypeReferences": true,
      "functions": false, // functions are hoisted so it's safe to use them before declaration, despite default is `true`
      "classes": true, // classes are not hoisted, so this should be prevented, default is `true`
      "variables": true, // This is what I have been talking in this issue, default is `true`
      "allowNamedExports": false // `export {...}` can be referenced safely. Actually default is also `false` 
  }]
}
```

```typescript
function foo() {
  bar() // bar can be safely called before `bar` declaration because `bar` is hoisted
}

function bar() {
 // ...
}
```
