### ISSUE TITLE
Prefer `inline-type-imports`

### ISSUE THREAD

**Issue by cuebit** [globalbrain/eslint-config#18]
Currently `type-imports` is the preferred option for `consistent-type-imports` where imported types from the same module are isolated. However, there seems to be a reoccurring theme with inline types as of late. 

Perhaps we should consider updating this options to apply this consistency and fix the style from `separate-type-imports` to `inline-type-imports`. This still allows type-only imports. 

```ts
// Bad
import { foo } from 'foo'
import type Foo from 'foo'
import type Bar from 'bar'

// Good
import { foo, type Foo } from 'foo'
import type Bar from 'bar'
```

**Comment by kiaking** [comment]
YES PLEASE

**Comment by kiaking** [comment]
@cuebit Is this possible? Could be nice to have 👀  Starting to get quite overwhelming fixing this syntax by hands 😅

**Comment by cuebit** [comment]
@kiaking yes it's possible but there are a caveat if you want to enforce auto-fixing (which is the aim here). To enable auto-fixing, all type imports will be inlined. That is, `import type` will become `import { type }`. Seems like this is what you are trying to achieve anyway. Are you OK with this?

**Comment by kiaking** [comment]
@cuebit You mean `type` always gets inside the bracket even if the all imports are "type", right?

```ts
import type { ABC } from '...'

// becomes

import { type ABC } from '...'
```

I'm personally fine with it, as long as it's fixed automatically 👍

@ryo-gk @NozomuIkuta @brc-dd Any preferences?

**Comment by cuebit** [comment]
> You mean `type` always gets inside the bracket even if the all imports are "type", right?

Yes. For fixing to work, type imports need to be of a fixed style.

**Comment by brc-dd** [comment]
I don't have any particular preference, but does `import { type ABC } from '...'` gets cleaned (tree shaken)?

IIRC it gets bundled to `import '...'`

`import type { ABC } from '...'` on the other hand is a type-only import that gets completely stripped.

`import { foo, type Foo } from 'foo'` is also fine, it gets compiled to `import { foo } from 'foo'` which is equivalent to what we get by `import { foo } from 'foo'; import type Foo from 'foo'`

We should once check this before adding auto fixing. Vite might have got smarter but I doubt as this is the standard TS behavior: https://typescript-eslint.io/rules/no-import-type-side-effects

**Comment by cuebit** [comment]
> I don't have any particular preference, but does import { type ABC } from '...' gets cleaned?

Yes. Refer to [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnAgnAvnAMyghDgHIQIATMgKFElmTUyQCE9DjSLq6Ho8AMJcS5SjVq10AD0bwkWADRw2KkbiA).

> We should once check this before adding auto fixing. Vite might have got smarter but I doubt as this is the standard TS behavior

It's standard behaviour when used with flags such as `importsNotUsedAsValues` and `preserveValueImports` prior to TS5.0. `verbatimSyntaxModule` will only be widely adopted by users of `importsNotUsedAsValues` and this pattern derived from older version of Angular (so you can thank them for complicating things).

However, this should not be of concern since these flags are somewhat unconventional in the GB ecosystem. As a bonus, @kiaking is very much against any form of linting aid from TS so these flags will continue to be unconventional.

Regarding Vite, esbuild handles static analysis of import declarations and specifiers and Vite transpiles in isolation. If there are any discrepancies in behaviour it would probably be upstream related to previous esbuild or rollup version.

> Can we enable both the rules (if they don't conflict with each other) to get the desired behavior

In theory, `no-import-type-side-effects` is not necessary for the reasons you mention. Enabling it will indeed conflict with the preferred specifier type because it will promote top-level type markers causing eslint to bail (to allow the user to decide preference) thus seemingly counterintuitive.

To conclude, the aim here is to identify which specifier is preferred (top-level or inline). Auto-fixing and linting in general will observe one or the other. Mixed specifiers is a foot-gun that will inevitably lead to confusion and won't prevent man in middle intervention.

If we decide to mix type specifiers for ambiguity reasons, we can achieve the following:

Consider this:
```ts
import { Ref, ref, unref } from 'vue'
```
will result in:
```ts
import { type Ref, ref, unref } from 'vue'
```

Where only a type is imported:
```ts
import { Ref } from 'vue'
```
will result in:
```ts
import type { Ref } from 'vue'
```

However, if existing imports are written as follows, they will be preserved and cannot be fixed:
```ts
import type { Ref } from 'vue'
import { ref, unref } from 'vue'
```

**Comment by cuebit** [comment]
@brc-dd if you know of any issues, or can bring to light the issues you have previously seen, this would be super helpful as it would give further clarity on the confidence vote. From my testing with TS4.5 through to 4.9 and as early as Vite 4.0.0 I have not been able to identify the issue. That said, I haven't tested every incremental version so I'm sure there may be versions that will indicate the discrepancy.

**Comment by kiaking** [comment]
Ah thanks for the insight! I'm bit confused here due to my lack of knowledge on TS compiler but what concerns me is what @brc-dd mentioned about `import { type ABC } from '...'` gets cleaned or not.

So if:

```ts
import { type ABC } from '...'
// becoms
import '...'
```

Then it might be problematic. Are you saying that this only happens when we set special compiler options such as `importsNotUsedAsValues` and `preserveValueImports` and etc, and if not, this doesn't happen (the type only imports gets cleaned)?

If the above my understanding is correct, then yeah I don't think we wouldn't use such special configs so I think we're safe 👀

**Comment by cuebit** [comment]
As a final thought, if at the end of this thread we cannot come to some form of conclusion I would suggest we keep things as is. There's a lot of talk about this in various forums of concern, so inevitably there may birth a rule that resolved this with ease. And I don't think this warrants exhausting days of investigations and testing 😅

**Comment by kiaking** [comment]
Yeah I agree. If this needs lots of investigation and discussions, I don't think its worth it 👍

**Comment by brc-dd** [comment]
> It's standard behaviour when used with flags such as importsNotUsedAsValues and preserveValueImports prior to TS5.0. verbatimSyntaxModule will only be widely adopted by users of importsNotUsedAsValues and this pattern derived from older version of Angular (so you can thank them for complicating things).

Ah, makes sense. I've had those flags enabled like from forever (on VitePress, etc.) 😅

So, if we are not planning on using those flags, we should be fine with this rule IMO.

**Comment by cuebit** [comment]
> Are you saying that this only happens when we set special compiler options such as `importsNotUsedAsValues` and `preserveValueImports` and etc, and if not, this doesn't happen (the type only imports gets cleaned)?

Essentially, yes. There are a lot of contributing factors that affect type elision but for the most part, and as far as the GB ecosystem is concerned, it's not something to worry about for your use cases. 

> If the above my understanding is correct, then yeah I don't think we wouldn't use such special configs so I think we're safe 👀 

Unless there's irrefutable evidence to suggest otherwise, I believe it's safe.

**Comment by cuebit** [comment]
> So, if we are not planning on using those flags, we should be fine with this rule IMO.

This is entirely my thinking and opinion also. Judging by the wider variety of projects at play, I don't think these flags will see the light of day. Unless you persuade Kia to build a library that utilises such wizardry.

**Comment by kiaking** [comment]
Great! Then, I think we add this rule 🤔  I think we're wise enough to remember this in case we tries to turn on those TS options in the future and act on it (currently, I don't think so

**Comment by cuebit** [comment]
The general consensus would be, if the vast majority of use cases benefit from a rule, the rule should be applicable. It can always be overridden for isolated use cases. 👍
