### ISSUE TITLE
Order `~...` above `@...`

### ISSUE THREAD

**Issue by kiaking** [globalbrain/eslint-config#35]
Due to our new icon import strategy, we import icons using `~...` path.

```ts
import IconMinusCircle from '~icons/ph/minus-circle-bold'
import IconTrash from '~icons/ph/trash-bold'
```

Currently, these gets ordered at the bottom but I want them to be placed above `@` stuff.

```ts
import IconMinusCircle from '~icons/ph/minus-circle-bold'
import IconTrash from '~icons/ph/trash-bold'
import { useComp } from '@/composables/Comp'
import MyComponent from './MyComponent.vue'
```

**Comment by cuebit** [comment]
Since ~/ is treated as @/ in nuxt, even if it’s not used, should we preserve this as internal paths? Or do we treat anything beginning with tilde as external?

**Comment by kiaking** [comment]
Good point. I think it is OK to treat anything beginning with tilde as external in our case 🤔 

@brc-dd 
What do you think?

**Comment by brc-dd** [comment]
We can treat them as external (at eslint level). Even on our nuxt projects we are adjusting order to suggest `@` before `~`. I don't think we are using tilde for anything other than icons 👀
