### ISSUE TITLE
Change how we format try catch

### ISSUE THREAD

**Issue by kiaking** [globalbrain/eslint-config#4]
Currently, it drops `catch` and `finally` to the next line. I would like to keep it in the same line 😅 

```ts
// Currently
try {
  // ...
}
catch (e) {
  // ...
}
finally {
  // ...
}
```

```ts
// I want it to be
try {
  // ...
} catch (e) {
  // ...
} finally {
  // ...
}
```

**Comment by cuebit** [comment]
Current rule enforces `stroustrup` option which equates to:

```js
if {
}
else if {
}
else {
}

try {
}
catch(e) {
}
finally {
}
```

Changing to `1tbs` will equate to:

```js
if {
} else if {
} else {
}

try {
} catch(e) {
} finally {
}
```

Happy to proceed?

**Comment by kiaking** [comment]
> Current configuration also allows braces on a single line:

Yeah I'm happy with this one. I almost never do it but if someone does it, I don't mind 👍
